### ISSUE TITLE
Date of Birth allows future dates

### ISSUE THREAD

**Issue by benji7890** [gcivil-nyu-org/nycCivilServiceJobs#129] opened 2020-11-25 18:11 UTC
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

You can put a future date in date of birth

## Expected Behavior
Last date to be inserted should be today's date

## Current Behavior
You can insert any future date

## Ideas for Improvement
Set a limit to today's date

## Steps to Reproduce
Go to create an account and edit date of birth

**Comment by gauravag2207** [comment] 2020-11-25 18:35
Hi @benji7890 ,

Thank you for pointing this out but this validation is not been put yet and the same is mentioned in the testing guide as well. So I suppose this would not be a bug. We will certainly take this as an enhancement 
![image](https://user-images.githubusercontent.com/55005259/100268343-7a278e80-2f1a-11eb-90a3-3788b587718c.png)

**Comment by gauravag2207** [comment] 2020-11-25 18:39
This is a duplicate of #127

**Comment by shivangpandya** [comment] 2020-11-30 16:32
As it is being tracked under #127 , closing the issue

**Closed as completed by shivangpandya** 2020-11-30 16:32 UTC
Labels: duplicate, enhancement
