### ISSUE TITLE
Starting Salary filter is slow

### ISSUE THREAD

**Issue by jgingh7** [gcivil-nyu-org/nycCivilServiceJobs#125] opened 2020-11-24 22:25 UTC
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior

A spinner or some indication that the filter is being processed is shown when filtering goes on for a long time.

## Current Behavior

The filter is done within 6 seconds after a certain starting salary is set.

## Ideas for Improvement

Implement an icon (possibly a spinner) that shows that the filtering is being processed.

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

I wasn't sure if my filter was working or not.

**Comment by i-rahman** [comment] 2020-11-24 22:31
Hi @jgingh7 , could you please elaborate the issue. We could not reproduce the issue at our end. 

Also, please note that we are filtering through data and our dataset is quite big as you will also see in Exam Result.

**Comment by jgingh7** [comment] 2020-11-24 22:35
The filtering using Agency, Civil Service Title, Postin Type, Part-time/Full-time, Career Level filtered instantly (<0.3 seconds)
But when I set filter for Starting Salary, say over $40,000, nothing changed until 6 seconds after I noticed that count for the result changed.

I do understand that you are using a large data, and I assume it is because of that,
but as a user, when I filtered for salary, I wasn't sure if it was working or not.

**Comment by i-rahman** [comment] 2020-11-24 22:41
Well thank you for this observation and good to know that the functionality is working. We will take this into our enhancement consideration.

**Comment by jgingh7** [comment] 2020-11-24 22:46
No problem! The app looks really solid and nice :)

**Comment by shivangpandya** [comment] 2020-12-02 20:08
Was fixed along with #128, hence closing it

**Closed as completed by shivangpandya** 2020-12-02 20:08 UTC
Labels: enhancement
