### ISSUE TITLE
BUG: Able to receive email for password reset even when account not activated(but user is created)

### ISSUE THREAD

**Issue by gururaj3** [gcivil-nyu-org/nycCivilServiceJobs#142] opened 2020-11-26 01:05 UTC
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

I created an account with email gss399@nyu.edu and I did not activate my account. Now, when I click on Password reset, I am still getting the reset link email to change my password. 

## Expected Behavior

According to me, we should first verify if the user is activated and then only send him/ her an password reset email. 

## Current Behavior

User can still reset his/ her password even when the account is not activated.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by shivangpandya** [comment] 2020-11-26 01:08
Hi 
Thank you for pointing it out. However, if you go through the testing doc the account email we are sending is just to give the user an email that an account is created.We don't need the email for verification
Hope that answers your question!

**Comment by gauravag2207** [comment] 2020-11-26 01:09
Hi @gururaj3 
We don't have the feature to verify the account. As soon as a user creates an account, it's active and we send a confirmation email. The same is mentioned in the testing guide as well.
So, this would not qualify as a bug. But we are looking into an enhancement to include email verification if time permits. If we do that, this would also be implemented.

Thanks

**Comment by shivangpandya** [comment] 2020-11-26 01:09
Hi
Thank you for pointing it out. However, if you go through the testing doc the account email we are sending is just to give the user an email that an account is created.We don't need the email for verification
Hope that answers your question!

**Comment by joshganguly** [comment] 2020-11-26 01:16
duplicate of #122

**Comment by shivangpandya** [comment] 2020-11-30 16:46
This is working as intended, the account is activated as soon as you register and hence you are able to reset your password

**Closed as completed by shivangpandya** 2020-11-30 16:46 UTC
Labels: invalid
