### ISSUE TITLE
Repetitive "Agency" options in the filter on the "Job" page

### ISSUE THREAD

**Issue by leelightman** [gcivil-nyu-org/nycCivilServiceJobs#139] opened 2020-11-26 00:11 UTC
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

When I click the "Agency" filter, there are repetitive options popping up. Please check the "Steps to Reproduce" sections for more details
## Steps to Reproduce

1. Search "Inspector" under Job tab https://nyc-civil-service-jobs.herokuapp.com/jobs/search/?q=inspector
2. Go to "Agency" filter and a list of options pops up
3. Repetitive categories show up (for example, dept of health/mental hygiene 3 times, NYC housing authority 3 times)
4.

**Comment by joshganguly** [comment] 2020-11-26 00:15
@leelightman this is a duplicate of #126. Please track this via #126 . Closing this.

**Closed as completed by joshganguly** 2020-11-26 00:15 UTC
Labels: duplicate
