### ISSUE TITLE
BUG: Able to create account completely with numbers

### ISSUE THREAD

**Issue by gururaj3** [gcivil-nyu-org/nycCivilServiceJobs#143] opened 2020-11-26 02:00 UTC
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Able to create an account by entering only numbers for Username, firstname, lastname

## Expected Behavior

Should not be able to create an account if the user enters only numbers

## Current Behavior

I can create an account by entering only the numbers

## Steps to Reproduce

1.
2.
3.
4.

**Comment by joshganguly** [comment] 2020-11-26 02:01
duplicate of #135

**Comment by gauravag2207** [comment] 2020-11-26 02:05
Hi @gururaj3 ,

I personally don't think this is a bug. There's nothing wrong with having numbers in name and user.

Thanks,
Gaurav

**Comment by shivangpandya** [comment] 2020-11-30 16:47
Working as intended

**Closed as completed by shivangpandya** 2020-11-30 16:47 UTC
Labels: duplicate, wontfix
